AllCops:
  NewCops: enable
Gemspec/RequireMFA:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: 'empty_lines'
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: 'empty_lines'
Layout/FirstArrayElementIndentation:
  EnforcedStyle: 'consistent'
Layout/FirstHashElementIndentation:
  EnforcedStyle: 'consistent'
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: 'require_space'
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/InterpolationCheck:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Style/BarePercentLiterals:
  EnforcedStyle: 'percent_q'
Style/BlockDelimiters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/CommandLiteral:
  EnforcedStyle: 'percent_x'
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: 'expanded'
Style/FormatString:
  EnforcedStyle: 'percent'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters: { '%i': '()', '%w': '()' }
Style/RaiseArgs:
  EnforcedStyle: 'compact'
Style/RedundantBegin:
  Enabled: false
Style/RegexpLiteral:
  AllowInnerSlashes: true
Style/RescueModifier:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: 'implicit'
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'comma'
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'
